In [9]:
# Artificial Neural Network

# Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.5.0'

In [10]:
# Part 1 - Data Preprocessing

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [11]:
dataset

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [12]:
dataset.iloc[:, 3:-1]

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female  ...          1               1        101348.88
1             608     Spain  Female  ...          0               1        112542.58
2             502    France  Female  ...          1               0        113931.57
3             699    France  Female  ...          0               0         93826.63
4             850     Spain  Female  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France    Male  ...          1               0         96270.64
9996          516    France    Male  ...          1               1        101699.77
9997          709    France  Female  ...          0               1         42085.58
9998          772   Germany    Male  ...          1               0         92888.52
9999          792    France  Female  ...          1               0         38190.78

[10000 rows x 10 columns]

In [13]:
# Encoding categorical data
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [14]:
data_cols=dataset.columns
data_cols

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [15]:
XX=pd.DataFrame(X)
XX

0        1  2   3   4        5  6  7  8        9
0     619   France  0  42   2        0  1  1  1   101349
1     608    Spain  0  41   1  83807.9  1  0  1   112543
2     502   France  0  42   8   159661  3  1  0   113932
3     699   France  0  39   1        0  2  0  0  93826.6
4     850    Spain  0  43   2   125511  1  1  1  79084.1
...   ...      ... ..  ..  ..      ... .. .. ..      ...
9995  771   France  1  39   5        0  2  1  0  96270.6
9996  516   France  1  35  10  57369.6  1  1  1   101700
9997  709   France  0  36   7        0  1  0  1  42085.6
9998  772  Germany  1  42   3  75075.3  2  1  0  92888.5
9999  792   France  0  28   4   130143  1  1  0  38190.8

[10000 rows x 10 columns]

In [16]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [17]:
XX=pd.DataFrame(X)

In [18]:
XX

0  1  2    3  4   5   6        7  8  9  10       11
0     1  0  0  619  0  42   2        0  1  1  1   101349
1     0  0  1  608  0  41   1  83807.9  1  0  1   112543
2     1  0  0  502  0  42   8   159661  3  1  0   113932
3     1  0  0  699  0  39   1        0  2  0  0  93826.6
4     0  0  1  850  0  43   2   125511  1  1  1  79084.1
...  .. .. ..  ... ..  ..  ..      ... .. .. ..      ...
9995  1  0  0  771  1  39   5        0  2  1  0  96270.6
9996  1  0  0  516  1  35  10  57369.6  1  1  1   101700
9997  1  0  0  709  0  36   7        0  1  0  1  42085.6
9998  0  1  0  772  1  42   3  75075.3  2  1  0  92888.5
9999  1  0  0  792  0  28   4   130143  1  1  0  38190.8

[10000 rows x 12 columns]

In [19]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
print(X)


[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


In [20]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [21]:
# Part 2 - Building the ANN

# Initializing the ANN
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))



In [22]:
# Part 3 - Training the ANN

# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)



Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5623 - accuracy: 0.7376
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4715 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4521 - accuracy: 0.7983
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4342 - accuracy: 0.8080
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4172 - accuracy: 0.8217
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3982 - accuracy: 0.8354
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3826 - accuracy: 0.8460
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3707 - accuracy: 0.8518
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3620 - accuracy: 0.8560
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3565 - accura

In [23]:
# Part 4 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [24]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1520   75]
 [ 197  208]]
