In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from keras.models import sequential
from keras.layers import Dense , SimpleRNN

In [ ]:
dataset_train = pd.read_csv('NSE-TATAGLOBAL.csv')
training_set = dataset_train.iloc[:, 1:2].values

In [ ]:
dataset_train.head()

Date    Open    High  ...   Close  Total Trade Quantity  Turnover (Lacs)
0  2018-09-28  234.05  235.95  ...  233.75               3069914          7162.35
1  2018-09-27  234.55  236.80  ...  233.25               5082859         11859.95
2  2018-09-26  240.00  240.00  ...  234.25               2240909          5248.60
3  2018-09-25  233.30  236.75  ...  236.10               2349368          5503.90
4  2018-09-24  233.55  239.20  ...  233.30               3423509          7999.55

[5 rows x 8 columns]

In [ ]:
training_set

array([[234.05],
       [234.55],
       [240.  ],
       ...,
       [121.8 ],
       [120.3 ],
       [122.1 ]])

In [ ]:
training_set.shape

(2035, 1)

In [ ]:
dataset_train.shape

(2035, 8)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)

In [ ]:
training_set_scaled

array([[0.6202352 ],
       [0.62226277],
       [0.64436334],
       ...,
       [0.16504461],
       [0.15896188],
       [0.16626115]])

In [ ]:
X_train = []
y_train = []
for i in range(60, 2035):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)

In [ ]:
X_train.shape

(1975, 60)

In [ ]:
y_train

array([0.77007299, 0.73641525, 0.73763179, ..., 0.16504461, 0.15896188,
       0.16626115])

In [ ]:
#convert to 3d
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

In [ ]:
X_train.shape

(1975, 60, 1)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [ ]:
regressor = Sequential()

regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

regressor.add(Dense(units = 1))

regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

regressor.fit(X_train, y_train, epochs = 100, batch_size = 32)

Epoch 1/100
62/62 [==============================] - 15s 127ms/step - loss: 0.0097
Epoch 2/100
62/62 [==============================] - 8s 128ms/step - loss: 0.0027
Epoch 3/100
62/62 [==============================] - 8s 127ms/step - loss: 0.0029
Epoch 4/100
62/62 [==============================] - 8s 127ms/step - loss: 0.0034
Epoch 5/100
62/62 [==============================] - 8s 128ms/step - loss: 0.0023
Epoch 6/100
62/62 [==============================] - 8s 126ms/step - loss: 0.0026
Epoch 7/100
62/62 [==============================] - 8s 126ms/step - loss: 0.0020
Epoch 8/100
62/62 [==============================] - 8s 127ms/step - loss: 0.0020
Epoch 9/100
62/62 [==============================] - 8s 127ms/step - loss: 0.0020
Epoch 10/100
62/62 [==============================] - 8s 128ms/step - loss: 0.0020
Epoch 11/100
62/62 [==============================] - 8s 129ms/step - loss: 0.0019
Epoch 12/100
62/62 [==============================] - 8s 127ms/step - loss: 0.0018
Epoch 13/100